[package]
name = "egui-sfml"
version = "0.1.0"
authors = ["crumblingstatue <radiantstatue@gmail.com>"]
edition = "2018"

[dependencies]
egui = "0.13.0"

[dependencies.sfml]
version = "0.16.0"
default-features = false
features = ["graphics"]
