[package]
name = "egui-sfml"
version = "0.1.0"
authors = ["crumblingstatue <radiantstatue@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.egui]
version = "0.11"

[dependencies.sfml]
version = "0.16.0"
default-features = false
features = ["graphics"]
