[package]
name = "egui-sfml"
version = "0.1.0"
authors = ["crumblingstatue <radiantstatue@gmail.com>"]
edition = "2018"

[dependencies]
egui = "0.14.0"

[dependencies.sfml]
git = "https://github.com/jeremyletang/rust-sfml.git"
default-features = false
features = ["graphics"]

[dev-dependencies]
egui_demo_lib = "0.14.0"
epi = "0.14.0"
